# Site settings
title: "Havin a BLaST"
email: "wianvos@xebia.com"
description: > # this means to ignore newlines until "baseurl:"
  Havin a blast is a blog dedicated to cool opensource infrastructure devops tech stuff. And other assorted BS.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
twitter_username: "nonexistent"
github_username:  "wianvos"

# Build settings
markdown: kramdown
